CREATE TABLE "APP"."EMPLOYEE"
(
   E_ID varchar(255)PRIMARY KEY NOT NULL,
   FIRST_NAME varchar(255),
   LAST_NAME varchar(255),
   PASSWORD varchar(60) NOT NULL
);


CREATE TABLE "APP"."CUSTOMER"
(
   C_ID INT PRIMARY KEY NOT NULL,
   DOB varchar(255),
   FIRST_NAME varchar(255),
   LAST_NAME varchar(255)
 
);

CREATE TABLE "APP"."SAVINGACCOUNT"
(
   CUSTOMERID INT,
   ACCNUM varchar(255),
   BALANCE INT
 
);

CREATE INDEX ACCNUM on "APP"."SAVINGACCOUNT"(ACCNUM);

ALTER TABLE "SAVINGACCOUNT"ADD FOREIGN KEY (CUSTOMERID)REFERENCES CUSTOMER(C_ID);