CREATE TABLE "APP"."EMPLOYEE"
(
   E_ID varchar(255)PRIMARY KEY NOT NULL,
   FIRST_NAME varchar(255),
   LAST_NAME varchar(255),
   PASSWORD varchar(60) NOT NULL
);


CREATE TABLE "APP"."CUSTOMER"
(
   C_ID INTEGER default GENERATED_BY_DEFAULT not null primary key,
   DOB varchar(255),
   FIRST_NAME varchar(255),
   LAST_NAME varchar(255)
 
);

CREATE TABLE "APP"."SAVINGACCOUNT"
(
   CUSTOMERID INT not null,
   ACCNUM varchar(255) not null,
   BALANCE INT
 
);

CREATE INDEX ACCNUM on "APP"."SAVINGACCOUNT"(ACCNUM);

ALTER TABLE "SAVINGACCOUNT"ADD FOREIGN KEY (CUSTOMERID)REFERENCES CUSTOMER(C_ID);